[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_scripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["openai~=1.6.1", "rich~=13.7.0", "tiktoken~=0.5.2"]
dynamic = ["version"]

[project.scripts]
ask-workspace = "ai_scripts.ask_workspace:main"
